### ISSUE TITLE
[🔭 Feature] 若是能有一个支持分布式可视化WebUI任务调度中心的实现就更好了.

### ISSUE THREAD

**Issue by joesdu** [MonkSoul/Sundial#1]
若是能有一个支持分布式可视化WebUI任务调度中心的实现就更好了.最好是支持多种存储方式,如:MongoDB,MSSQL,SQLite等.

**Comment by monksoul** [comment]
这个？

![image](https://github.com/MonkSoul/Sundial/assets/22766122/ef854d6c-dadb-47bf-ab05-7f8e5864a42d)

![image](https://github.com/MonkSoul/Sundial/assets/22766122/814a5752-1ae7-4bf1-b6e7-8d03aa360d38)

![image](https://github.com/MonkSoul/Sundial/assets/22766122/caaa578a-8fb2-4054-be19-1a35b802861a)
