### ISSUE TITLE
IJob任务实例未被正确释放

### ISSUE THREAD

**Issue by 0xlane** [MonkSoul/Sundial#2]
任务在同时实现 IJob 和 IDisposable 的时候，在 ISchedulerFactory 被释放或相关任务被删除的时候，任务Dispose方法未被调用。

当前只能先手动调用 builder.Services.AddSingleton 将任务注册到 IServiceCollection 中，最后终止程序时才能任务实例被正确释放。

**Comment by monksoul** [comment]
更新到最新版
